### ISSUE TITLE
Installing on Windows 10 64-bit plus getting images

### ISSUE THREAD

**Issue by shapecoder** [fehlfarbe/python-ids#1]
I've been trying to get this library to work on Windows 10 64-bit with 64-bit Python 3, but I've not been successful.

```
C:\python-ids-master>python setup.py install
running install
running bdist_egg
running egg_info
creating idscamera.egg-info
writing idscamera.egg-info\PKG-INFO
writing dependency_links to idscamera.egg-info\dependency_links.txt
writing requirements to idscamera.egg-info\requires.txt
writing top-level names to idscamera.egg-info\top_level.txt
writing manifest file 'idscamera.egg-info\SOURCES.txt'
file idscamera.py (for module idscamera) not found
reading manifest file 'idscamera.egg-info\SOURCES.txt'
writing manifest file 'idscamera.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
file idscamera.py (for module idscamera) not found
file idscamera.py (for module idscamera) not found
running build_ext
building '_idscamera' extension
creating build
creating build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/ -IC:\Users\me\AppData\Local\Programs\Python\Python36\include -IC:\Users\me\AppData\Local\Programs\Python\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpidscamera_wrap.cxx /Fobuild\temp.win-amd64-3.6\Release\idscamera_wrap.obj
idscamera_wrap.cxx
c1xx: fatal error C1083: Cannot open source file: 'idscamera_wrap.cxx': No such file or directory
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

Seems that swig is not executing properly, so I swigged it manually:

```
C:\python-ids-master>C:\swigwin-3.0.12\swig.exe -v -c++ -python idscamera.i && python setup.py build_ext --inplace
Language subdirectory: python
Search paths:
   .\
   .\swig_lib\python\
   C:\swigwin-3.0.12\Lib\python\
   .\swig_lib\
   C:\swigwin-3.0.12\Lib\
Preprocessing...
Starting language-specific parse...
Processing types...
C++ analysis...
Processing nested classes...
Generating wrappers...
running build_ext
building '_idscamera' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/ -IC:\Users\me\AppData\Local\Programs\Python\Python36\include -IC:\Users\me\AppData\Local\Programs\Python\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpidscamera_wrap.cxx /Fobuild\temp.win-amd64-3.6\Release\idscamera_wrap.obj
idscamera_wrap.cxx
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -I/usr/include/ -IC:\Users\me\AppData\Local\Programs\Python\Python36\include -IC:\Users\me\AppData\Local\Programs\Python\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpidscamera.cpp /Fobuild\temp.win-amd64-3.6\Release\idscamera.obj
idscamera.cpp
idscamera.cpp(29): warning C4101: 'formatInfo': unreferenced local variable
idscamera.cpp(54): warning C4800: 'INT': forcing value to bool 'true' or 'false' (performance warning)
idscamera.cpp(200): warning C4244: 'return': conversion from 'double' to 'int', possible loss of data
creating C:\python-ids-master\build\lib.win-amd64-3.6
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:C:\Users\me\AppData\Local\Programs\Python\Python36\libs /LIBPATH:C:\Users\me\AppData\Local\Programs\Python\Python36\PCbuild\amd64 "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\LIB\amd64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\10\lib\10.0.10240.0\ucrt\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\lib\um\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\8.1\lib\winv6.3\um\x64" ueye_api.lib /EXPORT:PyInit__idscamera build\temp.win-amd64-3.6\Release\idscamera_wrap.obj build\temp.win-amd64-3.6\Release\idscamera.obj /OUT:build\lib.win-amd64-3.6\_idscamera.cp36-win_amd64.pyd /IMPLIB:build\temp.win-amd64-3.6\Release\_idscamera.cp36-win_amd64.lib
idscamera_wrap.obj : warning LNK4197: export 'PyInit__idscamera' specified multiple times; using first specification
   Creating library build\temp.win-amd64-3.6\Release\_idscamera.cp36-win_amd64.lib and object build\temp.win-amd64-3.6\Release\_idscamera.cp36-win_amd64.exp
Generating code
Finished generating code
copying build\lib.win-amd64-3.6\_idscamera.cp36-win_amd64.pyd ->
```

Now I could run the setup :)

```
C:\python-ids-master>python setup.py install
running install
running bdist_egg
running egg_info
writing idscamera.egg-info\PKG-INFO
writing dependency_links to idscamera.egg-info\dependency_links.txt
writing requirements to idscamera.egg-info\requires.txt
writing top-level names to idscamera.egg-info\top_level.txt
reading manifest file 'idscamera.egg-info\SOURCES.txt'
writing manifest file 'idscamera.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
copying idscamera.py -> build\lib.win-amd64-3.6
running build_ext
creating build\bdist.win-amd64
creating build\bdist.win-amd64\egg
copying build\lib.win-amd64-3.6\idscamera.py -> build\bdist.win-amd64\egg
copying build\lib.win-amd64-3.6\_idscamera.cp36-win_amd64.pyd -> build\bdist.win-amd64\egg
byte-compiling build\bdist.win-amd64\egg\idscamera.py to idscamera.cpython-36.pyc
creating stub loader for _idscamera.cp36-win_amd64.pyd
byte-compiling build\bdist.win-amd64\egg\_idscamera.py to _idscamera.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying idscamera.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INFO
copying idscamera.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying idscamera.egg-info\dependency_links.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying idscamera.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG-INFO
copying idscamera.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EGG-INFO
writing build\bdist.win-amd64\egg\EGG-INFO\native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.idscamera.cpython-36: module references __file__
__pycache__._idscamera.cpython-36: module references __file__
creating dist
creating 'dist\idscamera-0.1-py3.6-win-amd64.egg' and adding 'build\bdist.win-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing idscamera-0.1-py3.6-win-amd64.egg
removing 'c:\users\me\appdata\local\programs\python\python36\lib\site-packages\idscamera-0.1-py3.6-win-amd64.egg' (and everything under it)
creating c:\users\me\appdata\local\programs\python\python36\lib\site-packages\idscamera-0.1-py3.6-win-amd64.egg
Extracting idscamera-0.1-py3.6-win-amd64.egg to c:\users\me\appdata\local\programs\python\python36\lib\site-packages
idscamera 0.1 is already the active version in easy-install.pth

Installed c:\users\me\appdata\local\programs\python\python36\lib\site-packages\idscamera-0.1-py3.6-win-amd64.egg
Processing dependencies for idscamera==0.1
Searching for numpy==1.11.3+mkl
Best match: numpy 1.11.3+mkl
Adding numpy 1.11.3+mkl to easy-install.pth file

Using c:\users\me\appdata\local\programs\python\python36\lib\site-packages
Finished processing dependencies for idscamera==0.1
```

The example.py was geared towards multiple camera's, so I just removed a lot of stuff:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import idscamera
import numpy as np

if __name__ == '__main__':
    cam = idscamera.IDSCamera()
    cam.set_auto_param()
    cam.start_capture()
    cam.exposure(1)

    img = cam.next()

    print(img[0])
```

Initially I got buffer errors:

```
Traceback (most recent call last):
  File "C:\Users\me\Desktop\example.py", line 13, in <module>
    img = cam.next()
  File "C:\Users\me\Desktop\idscamera.py", line 169, in next
    img = np.frombuffer(img, dtype=np.uint8, count=self.height() * self.width())
AttributeError: 'str' object has no attribute '__buffer__'
```

Which I fixed by adding .encode('utf-8') to img in the function definition of next:
```
img = np.frombuffer(img.encode('utf-8'), dtype=np.uint8, count=self.height() * self.width())
```
I don't get any errors anymore, but the array that should contain image data is just filled with zeros. I tried various combination of start_capture() and exposure() to no avail.

Any idea what this could be?

**Comment by fehlfarbe** [comment]
Hi, nice work!
I just created the Python wrapper to run two cameras with trigger cable to get synced images on linux, so I didn't test other setups but one camera should work.

Is every image just zeros if you run the capture in a loop? If not, change these two lines in the idscamera.cpp from `IS_DONT_WAIT` to `IS_WAIT` and recompile:
https://github.com/fehlfarbe/python-ids/blob/master/idscamera.cpp#L54
https://github.com/fehlfarbe/python-ids/blob/master/idscamera.cpp#L73

After changing these lines, the `cam.next()` method blocks until there is new image data. At the moment it's configured to return the latest image data from camera buffer.
